{% set name = "libzenohc" %}
{% set version = "1.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/eclipse-zenoh/zenoh-c/archive/refs/tags/{{ version }}.tar.gz
    sha256: 158a49b8e8468effbf932fe4eaee449f9055eb234cb73211a3ad59c308273d0d
    patches:
      - disable_static_library_install_part1.patch
      - disable_static_library_install_part2.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}
  # Workaround for https://github.com/conda-forge/zenoh-c-feedstock/issues/37
  skip: true  # [ppc64le]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cargo-bundle-licenses
    - cmake
    - ninja
    - pkg-config
  host:
    - zenoh-rust-abi {{ version }}.*
test:
  files:
    - examples_CMakeLists.txt
  source_files:
    - examples

  commands:
    - test -f ${PREFIX}/lib/libzenohc${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\lib\\zenohc.dll.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\zenohc.dll exit 1  # [win]
    # Ensure that static libraries are not packaged
    - test ! -f ${PREFIX}/lib/libzenohc.a  # [unix]
    - if exist %PREFIX%\\Library\\bin\\zenohc.lib exit 1  # [win]
    - cmake-package-check zenohc --targets zenohc::shared zenohc::lib
  requires:
    - cmake-package-check
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://github.com/eclipse-zenoh/zenoh-c
  license: Apache-2.0 OR EPL-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: C API for Zenoh

extra:
  # Stick to the repo name for the feedstock name
  feedstock-name: zenoh-c
  recipe-maintainers:
    - traversaro
